### ISSUE TITLE
handle description of classes/categories in QIF Files

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pynomina#24]
https://github.com/WolfgangFahl/pynomina/blob/main/nomina_examples/qifparser_test_file.qif
```
!Type:Class
Nmy class
Dexample class
^
```

```yaml
Class:my class:
    account_id: Class:my class
    name: my class
    account_type: CLASS
    description: example class
    parent_account_id: Class
```
